version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - database

  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: release-demo
      MYSQL_USER: root
      MYSQL_PASSWORD: admin12345
      MYSQL_ROOT_PASSWORD: admin12345...
